/**
 * TermsPage — Terms of Service for waterquality.trading.
 * Public route, no auth required.
 */

import React from 'react';
import styled from 'styled-components';

const Page = styled.div`
  min-height: 100vh;
`;

const Hero = styled.section`
  padding: 80px 24px 48px;
  background: #0B1120;
  color: #FFFFFF;

  @media (min-width: ${({ theme }) => theme.breakpoints.lg}px) {
    padding: 100px 24px 64px;
  }
`;

const HeroInner = styled.div`
  max-width: 720px;
  margin: 0 auto;
`;

const HeroTitle = styled.h1`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: clamp(28px, 4vw, 40px);
  font-weight: 800;
  letter-spacing: -0.03em;
  margin: 0 0 12px;
`;

const Updated = styled.p`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 14px;
  color: rgba(255, 255, 255, 0.45);
  margin: 0;
`;

const Content = styled.section`
  padding: 48px 24px 80px;
  background: ${({ theme }) => theme.colors.background};

  @media (max-width: 640px) {
    padding: 32px 16px 56px;
  }
`;

const Inner = styled.div`
  max-width: 720px;
  margin: 0 auto;
`;

const H2 = styled.h2`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 20px;
  font-weight: 700;
  color: ${({ theme }) => theme.colors.text};
  margin: 40px 0 12px;
  letter-spacing: -0.01em;

  &:first-of-type { margin-top: 0; }
`;

const P = styled.p`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 16px;
  color: ${({ theme }) => theme.colors.textSecondary};
  line-height: 1.7;
  margin: 0 0 16px;
`;

export default function TermsPage() {
  return (
    <Page>
      <Hero>
        <HeroInner>
          <HeroTitle>Terms of Service</HeroTitle>
          <Updated>Last Updated: February 2026</Updated>
        </HeroInner>
      </Hero>
      <Content>
        <Inner>
          <H2>1. Acceptance of Terms</H2>
          <P>By accessing or using waterquality.trading ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</P>

          <H2>2. Platform Description</H2>
          <P>WaterQuality.Trading is a marketplace for verified water quality nutrient credits. The Platform facilitates the listing, discovery, and transaction of nutrient removal credits generated by distributed water production systems and verified through BlueSignal monitoring infrastructure.</P>

          <H2>3. Eligibility</H2>
          <P>You must be at least 18 years old and capable of forming a binding contract. If you are using the Platform on behalf of an organization, you represent that you have authority to bind that organization.</P>

          <H2>4. Account Registration</H2>
          <P>You must provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity under your account. You must notify us immediately of any unauthorized use.</P>

          <H2>5. Credit Listings and Transactions</H2>
          <P>All nutrient credits listed on the Platform must be generated through verified monitoring systems and meet the Platform's verification requirements. Credit listings must accurately represent the type, quantity, and verification status of the credits offered. The Platform facilitates transactions but does not guarantee the performance of any credit or the outcome of any environmental program. Pricing is determined by utility-controlled rate structures and market conditions. All transactions are subject to verification confirmation before settlement.</P>

          <H2>6. Verification and Data Integrity</H2>
          <P>Credits are verified through a three-layer system: inline flow metering, BlueSignal continuous monitoring, and independent third-party sampling. The Platform relies on data from BlueSignal monitoring devices and third-party verification services. While we strive for accuracy, we do not guarantee that all data is error-free. Discrepancies identified through verification may result in credit adjustment, suspension, or revocation.</P>

          <H2>7. Fees and Payment</H2>
          <P>The Platform may charge transaction fees, service fees, or platform fees as disclosed at the time of transaction. Rebate amounts are determined by participating utilities and are subject to change. A platform service fee is deducted for monitoring, verification, and program management services.</P>

          <H2>8. Prohibited Conduct</H2>
          <P>You agree not to: submit fraudulent credit listings or falsified monitoring data; manipulate or interfere with the verification process; use the Platform for money laundering or other illegal financial activities; attempt to access other users' accounts or data; reverse engineer or disassemble any part of the Platform; use automated systems to scrape or collect data from the Platform.</P>

          <H2>9. Intellectual Property</H2>
          <P>All content, design, and technology on the Platform is owned by BlueSignal LTD or its licensors. You may not reproduce, distribute, or create derivative works without written permission.</P>

          <H2>10. Disclaimers</H2>
          <P>THE PLATFORM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. We do not guarantee that credits will maintain their value, that utility rebate programs will continue, or that regulatory frameworks will remain unchanged. Environmental outcomes depend on many factors outside our control.</P>

          <H2>11. Limitation of Liability</H2>
          <P>To the maximum extent permitted by law, BlueSignal LTD shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform.</P>

          <H2>12. Indemnification</H2>
          <P>You agree to indemnify and hold harmless BlueSignal LTD and its officers, directors, employees, and agents from any claims arising from your use of the Platform or violation of these Terms.</P>

          <H2>13. Modifications</H2>
          <P>We reserve the right to modify these Terms at any time. Material changes will be communicated through the Platform or via email. Continued use after modifications constitutes acceptance.</P>

          <H2>14. Governing Law</H2>
          <P>These Terms are governed by the laws of the State of Texas, without regard to conflict of law principles.</P>

          <H2>15. Contact</H2>
          <P>For questions about these Terms, visit our <a href="/contact" style={{ color: '#0052CC' }}>Contact page</a> or email the address listed there.</P>
        </Inner>
      </Content>
    </Page>
  );
}
