/**
 * TermsPage — Terms of Service for waterquality.trading.
 * Public route, no auth required.
 */

import { useEffect } from 'react';
import styled from 'styled-components';

const Page = styled.div`
  min-height: 100vh;
`;

const Hero = styled.section`
  padding: 48px 24px 40px;
  background: #0B1120;
  color: #FFFFFF;

  @media (min-width: ${({ theme }) => theme.breakpoints.lg}px) {
    padding: 64px 24px 48px;
  }
`;

const HeroInner = styled.div`
  max-width: 720px;
  margin: 0 auto;
`;

const HeroTitle = styled.h1`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: clamp(28px, 4vw, 40px);
  font-weight: 800;
  letter-spacing: -0.03em;
  color: #FFFFFF;
  margin: 0 0 12px;
`;

const Updated = styled.p`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 14px;
  color: rgba(255, 255, 255, 0.45);
  margin: 0;
`;

const Content = styled.section`
  padding: 48px 24px 80px;
  background: ${({ theme }) => theme.colors.background};

  @media (max-width: 640px) {
    padding: 32px 16px 56px;
  }
`;

const Inner = styled.div`
  max-width: 720px;
  margin: 0 auto;
`;

const H2 = styled.h2`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 20px;
  font-weight: 700;
  color: ${({ theme }) => theme.colors.text};
  margin: 40px 0 12px;
  letter-spacing: -0.01em;

  &:first-of-type { margin-top: 0; }
`;

const P = styled.p`
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 16px;
  color: ${({ theme }) => theme.colors.textSecondary};
  line-height: 1.7;
  margin: 0 0 16px;
`;

const BackLink = styled.a`
  display: inline-block;
  font-family: ${({ theme }) => theme.fonts.sans};
  font-size: 14px;
  color: rgba(255, 255, 255, 0.6);
  text-decoration: none;
  margin-bottom: 16px;
  transition: color 0.15s;

  &:hover {
    color: #FFFFFF;
  }
`;

export default function TermsPage() {
  useEffect(() => { document.title = 'Terms of Service — WaterQuality.Trading'; }, []);
  return (
    <Page>
      <Hero>
        <HeroInner>
          <HeroTitle>Terms of Service</HeroTitle>
          <Updated>Last Updated: March 2026</Updated>
        </HeroInner>
      </Hero>
      <Content>
        <Inner>
          <H2>1. Acceptance of Terms</H2>
          <P>By accessing or using waterquality.trading ("the Platform"), operated by BlueSignal LTD ("BlueSignal", "we", "us", "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Platform.</P>

          <H2>2. Platform Description</H2>
          <P>WaterQuality.Trading is a marketplace for verified water quality nutrient credits. The Platform facilitates the listing, discovery, and transaction of nutrient removal credits — including AWG (nutrient removal) credits — generated by distributed water production systems and verified through BlueSignal monitoring infrastructure. The Platform connects credit producers, buyers, utilities, and verification partners within a regulated environmental marketplace.</P>

          <H2>3. Eligibility</H2>
          <P>You must be at least 18 years old and capable of forming a binding contract under applicable law. If you are using the Platform on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.</P>

          <H2>4. Account Registration</H2>
          <P>To access certain features, you must create an account. You agree to: provide accurate, current, and complete information during registration; maintain the security of your account credentials; accept responsibility for all activity under your account; notify us immediately of any unauthorized access or use. We reserve the right to suspend or terminate accounts that contain inaccurate information or violate these Terms.</P>

          <H2>5. Credit Listings and Transactions</H2>
          <P>All nutrient credits listed on the Platform must be generated through verified monitoring systems and meet the Platform's verification requirements. Credit listings must accurately represent the type, quantity, source location, and verification status of the credits offered. The Platform facilitates transactions but does not guarantee the performance of any credit or the outcome of any environmental program. Pricing is influenced by utility-controlled rate structures, regional demand, and market conditions. All transactions are subject to verification confirmation before settlement. Credits may be subject to adjustment or revocation if verification discrepancies are identified post-transaction.</P>

          <H2>6. Verification and Data Integrity</H2>
          <P>Credits are verified through a three-layer system: (1) inline flow metering at the point of production, (2) continuous monitoring via BlueSignal WQM-1 devices measuring pH, TDS, turbidity, ORP, and temperature, and (3) independent third-party sampling and laboratory analysis. While we strive for the highest accuracy, we do not guarantee that all data is error-free. Discrepancies identified through any verification layer may result in credit adjustment, suspension, or revocation. Users acknowledge that environmental data is inherently variable and subject to sensor calibration tolerances.</P>

          <H2>7. Fees and Payment</H2>
          <P>The Platform charges transaction fees, service fees, and platform fees as disclosed at the time of each transaction. Rebate amounts are determined by participating utilities and municipalities and are subject to change without notice from BlueSignal. A platform service fee is deducted for monitoring, verification, credit issuance, and program management services. All fees are non-refundable unless otherwise stated. Payment processing is handled by third-party providers subject to their own terms.</P>

          <H2>8. Prohibited Conduct</H2>
          <P>You agree not to: submit fraudulent credit listings or falsified monitoring data; manipulate, tamper with, or interfere with the verification process or monitoring devices; use the Platform for money laundering, terrorist financing, or other illegal financial activities; attempt to access other users' accounts, data, or private information; reverse engineer, decompile, or disassemble any part of the Platform; use automated bots, scrapers, or other systems to collect data from the Platform without authorization; circumvent any security measures or access controls; create multiple accounts for deceptive purposes.</P>

          <H2>9. Intellectual Property</H2>
          <P>All content, design, software, trademarks, and technology on the Platform is owned by BlueSignal LTD or its licensors and is protected by applicable intellectual property laws. You may not reproduce, distribute, modify, or create derivative works without prior written permission. Your use of the Platform does not grant you any ownership rights in Platform content or technology.</P>

          <H2>10. Disclaimers</H2>
          <P>THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not guarantee that credits will maintain their value, that utility rebate programs will continue, that regulatory frameworks will remain unchanged, or that the Platform will be uninterrupted or error-free. Environmental outcomes depend on many factors outside our control.</P>

          <H2>11. Limitation of Liability</H2>
          <P>To the maximum extent permitted by law, BlueSignal LTD and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Platform. Our total liability for any claim arising under these Terms shall not exceed the amount you paid to BlueSignal in the twelve (12) months preceding the claim.</P>

          <H2>12. Indemnification</H2>
          <P>You agree to indemnify, defend, and hold harmless BlueSignal LTD and its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising from your use of the Platform, your violation of these Terms, or your violation of any rights of a third party.</P>

          <H2>13. Dispute Resolution</H2>
          <P>Any dispute arising from these Terms or your use of the Platform shall first be subject to good-faith negotiation. If unresolved within thirty (30) days, disputes shall be resolved through binding arbitration in Travis County, Texas, in accordance with the rules of the American Arbitration Association. You agree to waive any right to participate in a class action lawsuit or class-wide arbitration.</P>

          <H2>14. Modifications</H2>
          <P>We reserve the right to modify these Terms at any time. Material changes will be communicated through the Platform, via email, or through a prominent notice at least thirty (30) days before they take effect. Continued use of the Platform after modifications take effect constitutes acceptance of the revised Terms.</P>

          <H2>15. Governing Law</H2>
          <P>These Terms are governed by and construed in accordance with the laws of the State of Texas, without regard to conflict of law principles. Any legal proceedings not subject to arbitration shall be brought in the state or federal courts located in Travis County, Texas.</P>

          <H2>16. Contact</H2>
          <P>For questions about these Terms, visit our <a href="/contact" style={{ color: '#0052CC' }}>Contact page</a> or email us at hello@bluesignal.xyz.</P>
        </Inner>
      </Content>
    </Page>
  );
}
